/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test1;

import java.awt.Color;

/**
 *
 * @author Internet
 */
public class Ventana extends javax.swing.JFrame {

    public int numeros[] =new int[100];
    public int indice=0;
    public int extender;
    /**
     * Creates new form ventana
     */
    public Ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        numero = new javax.swing.JTextField();
        resultado = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        agregar = new javax.swing.JButton();
        mostrar = new javax.swing.JButton();
        ordenar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Test");
        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(540, 400));

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        numero.setBackground(new java.awt.Color(149, 165, 166));
        numero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroKeyTyped(evt);
            }
        });
        jPanel3.add(numero);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        resultado.setBackground(new java.awt.Color(189, 195, 199));
        resultado.setOpaque(true);
        getContentPane().add(resultado, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(189, 195, 199));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        agregar.setBackground(new java.awt.Color(230, 126, 34));
        agregar.setText("Agregar");
        agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agregarMouseExited(evt);
            }
        });
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        jPanel1.add(agregar);

        mostrar.setBackground(new java.awt.Color(39, 174, 96));
        mostrar.setText("Mostrar");
        mostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mostrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mostrarMouseExited(evt);
            }
        });
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });
        jPanel1.add(mostrar);

        ordenar.setBackground(new java.awt.Color(231, 76, 60));
        ordenar.setText("Ordenar");
        ordenar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ordenarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ordenarMouseExited(evt);
            }
        });
        ordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenarActionPerformed(evt);
            }
        });
        jPanel1.add(ordenar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        //resultado.setText(numero.getText());
        numeros[indice]=Integer.parseInt(numero.getText());
        indice++;
    }//GEN-LAST:event_agregarActionPerformed

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        // TODO add your handling code here:
        for (int i=0;i<indice;i++)
        {
            resultado.setText(resultado.getText()+ numeros[i]+" ");
        }
    }//GEN-LAST:event_mostrarActionPerformed

    private void ordenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenarActionPerformed
        // TODO add your handling code here:
        resultado.setText(" ");
        for (int i = 0; i < indice; i++) {
            for (int contador = 0; contador < indice - 1; contador++) 
            {
                if (numeros[contador] > numeros[contador + 1]) 
                {
                    extender = numeros[contador];
                    numeros[contador] = numeros[contador + 1];
                    numeros[contador + 1] = extender;
                }
            }
        }
        for(int i=0;i<indice;i++) {
            resultado.setText(resultado.getText()+numeros[i]+" ");
        }
    }//GEN-LAST:event_ordenarActionPerformed

    private void numeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroKeyTyped
        // TODO add your handling code here:
       int key= evt.getKeyChar();
       boolean entrada=key>=48 && key <=57;
       if (!entrada)
       {
           evt.consume();
       }
    }//GEN-LAST:event_numeroKeyTyped

    private void agregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarMouseEntered
        // TODO add your handling code here:
        agregar.setBackground(new java.awt.Color(230,126,34));
    }//GEN-LAST:event_agregarMouseEntered

    private void agregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarMouseExited
        // TODO add your handling code here:
        agregar.setBackground(new java.awt.Color(52,73,94));
    }//GEN-LAST:event_agregarMouseExited

    private void mostrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarMouseExited
        // TODO add your handling code here:
        mostrar.setBackground(new java.awt.Color(52,73,94));
    }//GEN-LAST:event_mostrarMouseExited

    private void ordenarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordenarMouseExited
        // TODO add your handling code here:
        ordenar.setBackground(new java.awt.Color(52,73,94));
    }//GEN-LAST:event_ordenarMouseExited

    private void mostrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarMouseEntered
        // TODO add your handling code here:
        mostrar.setBackground(new java.awt.Color(39,174,96));
    }//GEN-LAST:event_mostrarMouseEntered

    private void ordenarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordenarMouseEntered
        // TODO add your handling code here:
        ordenar.setBackground(new java.awt.Color(231,76,60));
    }//GEN-LAST:event_ordenarMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton mostrar;
    private javax.swing.JTextField numero;
    private javax.swing.JButton ordenar;
    private javax.swing.JLabel resultado;
    // End of variables declaration//GEN-END:variables
}
